#!/usr/bin/env zsh

local root="$HOME/python/ipykernel-venvs"
local venv_name=$1
local venv_dir=$root"/"$venv_name
local venv_activate=$venv_dir"/bin/activate"

if [ -z $venv_name ]; then
  echo "missing ipykernel name as an argument"
  exit 1
fi

if [ ! -d $root ]; then
  mkdir $root
fi

if [ -f $venv_activate ]; then
  echo "virtual environment" $venv_name "exists"
  exit 1
fi

if [ ! -z $VIRTUAL_ENV_PROMPT ]; then
  deactivate
fi


virtualenv $venv_dir
source $venv_activate
pip install ipykernel
python3 -m ipykernel install --user --name=$venv_name

