#!/usr/bin/env zsh

local root="$HOME/python/ipykernel-venvs"
local venv_name=$1
local venv_dir=$root"/"$venv_name
local venv_activate=$venv_dir"/bin/activate"

if [ ! -f $venv_activate ]; then
  echo "virtual environment" $venv_name "not found"
  exit 1
fi
source $venv_activate
